### ISSUE TITLE
A possible to Install Pre-Installed windows images using installimage script? Working Tutorial provided!

### ISSUE THREAD

**Issue by ARHAEEM** [hetzneronline/installimage#108]
Hello guys, just found this guy made tutorial with hetzner to install windows automatically using console only: https://lowendtalk.com/discussion/196165/install-windows-server-on-any-vps-or-dedicated-server-without-kvm-ilo-or-ipmi

I was thinking why not converting it to installimage script?

> This could save a lot of time ordering KVM for dedicated servers owners! And a way easier than this https://community.hetzner.com/tutorials/install-windows/

**Comment by asciiprod** [comment]
Installimage scope is limited to Linux distribution, specifically those offered as options for our dedicated servers. If you have purchased a Windows license from us, then the installation is not done via installimage. Hence supporting 3rd party Windows-installations will likely never become part of installimage.
