### ISSUE TITLE
support for rootfs on btrfs subvolume

### ISSUE THREAD

**Issue by EddyBuhler** [hetzneronline/installimage#11]
Is it possible to add configuration options to allow having "/" on a btrfs subvolume, i.e. something like this:

PART swap swap 4G
PART boot ext3 1G
PART btrfsvol btrfs all
PART / btrfs  20G btrfsvol rootfs
PART /home btrfs 100G btrfsvol home

or similar?

**Comment by asciiprod** [comment]
Not that simple. It would need similar (and probably more) work like LVM support. So unlikely to happen in the near future

**Comment by EddyBuhler** [comment]
That's too bad, because it would open up a lot of extra possibilities, like taking btrfs snapshots from the rootfs and being able to put the whole server back into a working state when e.g. an update fails, similarly to how SUSE do with snapper. 

Thanks for the response, though!

**Comment by asciiprod** [comment]
We are currently testing an implementation internally. If there are now major issues, we will enable the code in our infrastructure and merge it here.
