### ISSUE TITLE
centos 6.10 error

### ISSUE THREAD

**Issue by 1265578519** [hetzneronline/installimage#12]
![qq 20190219001705](https://user-images.githubusercontent.com/6442439/52963801-b6d86480-33db-11e9-850b-29daffe4783a.png)

**Comment by asciiprod** [comment]
This message is entirely unrelated to the OS you are trying to install. It just means that the disk is still in use by something. While installimage tries to stop any RAID or LVM before it starts, it cannot address all possible causes which may trigger this.
