### ISSUE TITLE
EFI partition type

### ISSUE THREAD

**Issue by deric** [hetzneronline/installimage#16]
`bios_grub` seems to be [supported type](https://github.com/hetzneronline/installimage/blob/6c1a330af3cc9ee6af4c1b19f13fc7d4bb5a8fd2/functions.sh#L1038), however calling `mkfs.bios_grub` fails (not surprisingly). 

Is there other way how to create an EFI partition?

**Comment by asciiprod** [comment]
bios_grub is a special partition type required for grub when using GPT with legacy/BIOS mode. Currently installimage has no support installing OS in UEFI mode.

**Comment by asciiprod** [comment]
Please do not resurrect old issues. Installimage supports UEFI installations.
If you have a problem with a specific server models, please open a support request
