### ISSUE TITLE
Centos 8 fails with networkd missing

### ISSUE THREAD

**Issue by sandrich** [hetzneronline/installimage#20]
Hi

I am trying to install Centos 8 using installimage. The installation fails with networkd given that Centos 8 does not use networkd but NetworkManager instead

> [18:55:25] # use config file config.txt for autosetup
> [18:55:25] # OPT_CONFIGFILE:   /root/config.txt
> [18:55:25] # starting installimage on [ 138.201.140.245 ]
> [18:55:25] -------------------------------------
> [18:55:25] :   Hardware data:
> [18:55:25] :   CPU1: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (Cores 16)
> [18:55:25] :   Memory:  64338 MB
> [18:55:25] :   Disk /dev/nvme0n1: 1024 GB (=> 953 GiB)
> [18:55:25] :   Disk /dev/nvme1n1: 1024 GB (=> 953 GiB)
> [18:55:25] :   Total capacity 1907 GiB with 2 Disks
> [18:55:25] -------------------------------------
> [18:55:25] # make clean config
> [18:55:26] # executing autosetup ...
> [18:55:26] # checking if the script is disabled
> [18:55:26] # validating config ...
> [18:55:26] :   /boot : 512
> [18:55:26] :   lvm : all
> [18:55:27] :   Size of smallest drive is 1024209543168
> [18:55:27] Calculated size of array is: 1024209543168
> [18:55:27] :   setting TAR to GNUtar
> [18:55:27] :   setting TAR to GNUtar
> [18:55:27] checking if hdd sizes are within tolerance. min: 1024209543168 / max: 1382682883276
> [18:55:27] DRIVE1 in range
> [18:55:27] :   1024209543168
> [18:55:27] DRIVE2 in range
> [18:55:27] :   1024209543168
> [18:55:27] :   check_dos_partitions
> [18:55:47] # executing installfile ...
> [18:55:47] :   /boot : 512
> [18:55:47] :   lvm : all
> [18:55:47] :   check_dos_partitions
> [18:55:47] # load centos specific functions...
> [18:55:47] # Deleting partitions
> [18:55:48] # Deleting partitions on /dev/nvme0n1
> [18:55:49] # Deleting partitions on /dev/nvme1n1
> [18:55:51] # Test partition size
> [18:55:51] :   check_dos_partitions
> [18:55:51] # Creating partitions and /etc/fstab
> [18:55:51] # Creating partitions on /dev/nvme0n1
> [18:55:51] :   deactivate all dm-devices with dmraid and dmsetup
> [18:55:51] :   no block devices found
> [18:55:51] :   create partition: parted -s /dev/nvme0n1 mkpart primary ext3 2048s 1050623s
> [18:55:51] :   create partition: parted -s /dev/nvme0n1 mkpart primary ext3 1050624s 2000407215s
> [18:55:52] :   reread partition table after 5 seconds
> [18:55:57] :   deactivate all dm-devices with dmraid and dmsetup
> [18:55:57] :   no block devices found
> [18:55:57] # Creating partitions on /dev/nvme1n1
> [18:55:57] :   deactivate all dm-devices with dmraid and dmsetup
> [18:55:57] :   no block devices found
> [18:55:57] :   create partition: parted -s /dev/nvme1n1 mkpart primary ext3 2048s 1050623s
> [18:55:58] :   create partition: parted -s /dev/nvme1n1 mkpart primary ext3 1050624s 2000407215s
> [18:55:58] :   reread partition table after 5 seconds
> [18:56:03] :   deactivate all dm-devices with dmraid and dmsetup
> [18:56:03] :   no block devices found
> [18:56:03] # Creating software RAID level 1
> [18:56:03] # create software raid array(s)
> [18:56:03] :   Line is: "proc /proc proc defaults 0 0"
> [18:56:03] :   Line is: "devpts /dev/pts devpts gid=5,mode=620 0 0"
> [18:56:03] :   Line is: "tmpfs /dev/shm tmpfs defaults 0 0"
> [18:56:03] :   Line is: "sysfs /sys sysfs defaults 0 0"
> [18:56:03] :   Line is: "/dev/nvme1n1p1 /boot ext4 defaults 0 0"
> [18:56:03] Array RAID Level is: '1' -  -
> [18:56:03] Array metadata is: '--metadata=1.2'
> [18:56:03] :   Line is: "# /dev/nvme1n12 belongs to LVM volume group 'vg0'"
> [18:56:03] Array RAID Level is: '1' -  -
> [18:56:03] Array metadata is: '--metadata=1.2'
> [18:56:03] :   mdadm: /dev/nvme0n1p2 appears to be part of a raid array:
> [18:56:03] :   level=raid1 devices=2 ctime=Fri Oct 11 17:16:58 2019
> [18:56:03] :   mdadm: /dev/nvme1n1p2 appears to be part of a raid array:
> [18:56:03] :   level=raid1 devices=2 ctime=Fri Oct 11 17:16:58 2019
> [18:56:04] # Creating LVM volumes
> [18:56:04] # Removing all Logical Volumes and Volume Groups
> [18:56:04] # Removing all Physical Volumes
> [18:56:04] # Creating PV /dev/md/1
> [18:56:04] :   /dev/md/1: 8 bytes were erased at offset 0x00000200 (gpt): 45 46 49 20 50 41 52 54
> [18:56:04] :   /dev/md/1: 2 bytes were erased at offset 0x000001fe (PMBR): 55 aa
> [18:56:04] :   Physical volume "/dev/md/1" successfully created.
> [18:56:04] # Creating VG vg0 with PV /dev/md/1
> [18:56:04] :   Volume group "vg0" successfully created
> [18:56:04] # Creating LV vg0/root (51200 MiB)
> [18:56:04] :   Wiping xfs signature on /dev/vg0/root.
> [18:56:04] :   Logical volume "root" created.
> [18:56:04] # Creating LV vg0/swap (8192 MiB)
> [18:56:05] :   Logical volume "swap" created.
> [18:56:05] # Creating LV vg0/tmp (30720 MiB)
> [18:56:05] :   Logical volume "tmp" created.
> [18:56:09] # formatting  /dev/md/0  with  ext4
> [18:56:13] # formatting  /dev/vg0/root  with  xfs
> [18:56:17] # formatting  /dev/vg0/swap  with  swap
> [18:56:18] :   Setting up swapspace version 1, size = 8 GiB (8589930496 bytes)
> [18:56:18] :   no label, UUID=13dacd13-a3a6-4248-a2a6-d32bc08a47e2
> [18:56:22] # formatting  /dev/vg0/tmp  with  xfs
> [18:56:22] # Mounting partitions
> [18:56:22] # Sync time via ntp
> [18:56:22] :   Using standard Hetzner Online GmbH pubkey: /root/.oldroot/nfs/install/gpg/public-key.asc
> [18:56:22] :   Using standard Hetzner Online GmbH pubkey: /root/.oldroot/nfs/install/gpg/public-key-2018.asc
> [18:56:22] :   gpg: keybox '/root/.gnupg/pubring.kbx' created
> [18:56:22] :   gpg: /root/.gnupg/trustdb.gpg: trustdb created
> [18:56:22] :   gpg: key 9E03E2BEB8F0F463: public key "Hetzner Online AG, RZ-Softwareentwicklung (Signing Key 2013) <info@hetzner.de>" imported
> [18:56:22] :   gpg: Total number processed: 1
> [18:56:22] :   gpg:               imported: 1
> [18:56:22] :   gpg: key 7030DBE4387333B3: public key "Hetzner Online GmbH image signing key <info@hetzner.com>" imported
> [18:56:22] :   gpg: Total number processed: 1
> [18:56:22] :   gpg:               imported: 1
> [18:56:22] # Validating image before starting extraction
> [18:56:22] # Extracting image (local)
> [18:56:30] # Setting up network config
> [18:56:30] # setup network config
> [18:56:30] # setup /etc/systemd/network files
> [18:56:30] # setting up /etc/systemd/network/10-mainif.network
> [18:56:30] # Systype: B360 HD3P-LM
> [18:56:30] # Manufacturer: Gigabyte Technology Co., Ltd.
> [18:56:30] # Systype: B360 HD3P-LM
> [18:56:30] # Manufacturer: Gigabyte Technology Co., Ltd.
> [18:56:30] # chroot: systemctl enable systemd-networkd
> [18:56:30] :   Failed to enable unit, unit systemd-networkd.service does not exist.
> [18:56:30] => FAILED
> [18:56:30] :   report install.conf to rz-admin: 1267528
> [18:56:31] :   report debug.txt to rz-admin: ok
> [18:56:31] cleaning up

**Comment by asciiprod** [comment]
installimage currently does not support CentOS 8. It will be added when the images for our dedicated servers are ready.
