### ISSUE TITLE
Option: copy no files

### ISSUE THREAD

**Issue by ygoe** [hetzneronline/installimage#22]
I'm using this script to set up new servers. It does two things here: Prepare the disks, RAID, LVM and file systems; and copy the OS files (including making necessary changes to the config files).

When restoring a server from a file-based backup, no OS files need to be copied from a default image. I only need the disk preparation parts of this script, then I can restore all files in the file system from my backup.

It would be helpful to have an option to this script that only performs the first part and then does not copy any files into the new file system(s).

**Comment by asciiprod** [comment]
You can achieve this effect by passing an empty tar.gz (with a valid name) to installimage.
It will then break (when it tries to customize the system), but partitions and LVM is set up at this point.
Which is basically what you wanted
