### ISSUE TITLE
ZFS

### ISSUE THREAD

**Issue by MGAndreasen** [hetzneronline/installimage#23]
Where is the option to setup Debian or Proxmox on  ZFS

**Comment by asciiprod** [comment]
ZFS is currently not supported in installimage. There are currently no plans to add such support. Also the licensing situation around ZFS is problematic

**Comment by sskras** [comment]
@MGAndreasen, these scripts might help:

(in Bash) https://github.com/saveriomiroddi/zfs-installer
(Ansible) https://github.com/tijszwinkels/hetzner-ubuntu-16.04-zfs-root-ansible/

**Comment by MGAndreasen** [comment]
Ty. I did the installation manually with a pair og nvme drives with zfs mirror on hetzner as i needed a quick solution.  But thanks for the hint.
