### ISSUE TITLE
Support for RHEL?

### ISSUE THREAD

**Issue by jeichler** [hetzneronline/installimage#27]
Hi there,

would it be possible to add support for rhel as well?
It might be fairly close to the current centos logic, but users would not need to
- use centos in the image name
- ignore errors at the end of installimage (because of the update, since it's mostly not susbcribed yet)

Just checking whether in general you would be fine before looking into actually doing it to create a PR which might be rejected because not wanted :)

**Comment by asciiprod** [comment]
Thanks for the suggestion. As you have pointed out, RHEL is generally installable by using centos as image name. As installimage is primarily used internally to provision ordered servers, we are a bit reluctant to add code that we cannot test ourselves. However, if your PR is small and non-invasive, we can look into merging it.
