### ISSUE TITLE
Avoid removing partitions?

### ISSUE THREAD

**Issue by m3nu** [hetzneronline/installimage#33]
From what I see in the code, all existing partitions are always deleted in `delete_partitions()`?

Is it possible to keep some existing data partitions around, while reinstalling the system drive at `/`?

This is for the storage servers I'm running with Hetzner. With the CentOS 8 end of life change, I'm afraid I may need to reinstall them sooner than expected. 😟

If it's not possible, what would be the next-best way to preserve partitions? KVM/VNC installation?

**Comment by asciiprod** [comment]
Installimage always creates a new partition table, but that does not remove the data. 
If your data is stored in a separate partition, you can re-install without it and then re-create the partition again afterwards.
For example, initial install config:

```
PART /boot ext3 1G
PART / 20G
PART /data all
```

Then you can leave out the data partition on the re-install
```
PART /boot ext3 1G
PART / 20G
```

and afterwards manually re-add the data partition at the exact same sector and size as before and your data will be there.

**Comment by JevinG** [comment]
Hi,

Would it still work for root which is on an lv : /dev/data/root (to be formatted) and data is present in LVs in the same Volume group ( to remain intact ) ?

**Comment by floe** [comment]
I did this today and it worked, but it's a highly fragile approach, one sector off and you're busted. Since I found this issue first,  other folks might arrive here as well, but there is a less dangerous option described in #109 by using the hidden config options `PRESERVE_FS` and `REUSE_FSTAB`.
