### ISSUE TITLE
ERROR: Value for CRYPTPASSWORD is not defined

### ISSUE THREAD

**Issue by sneakyx** [hetzneronline/installimage#34]
I tried to install a new server, but I get this error after editing the config file. 
In the config file there is no comment for this setting.
I tried 
`CRYPTPASSWORD 1234` but that didn't work either. Is there a possibility to install server without cryptpassword?

Thanks.

**Comment by sneakyx** [comment]
before I started `installimage` I had to set `CRYPT=0`
I don't know if this behave as intended.

**Comment by asciiprod** [comment]
Thanks, there was a missing check.

**Comment by sneakyx** [comment]
So is it fixed? I didn't find something that mentioned this issue.

**Comment by asciiprod** [comment]
Yes, it should be. If you still have issues, please open a support request with the config you are using.
The commits in this repository do not reflect or mention issues reported via Github.

**Comment by asciiprod** [comment]
Are you using installimage on a Hetzner Server or are you using this repository in your own infrastructure?

**Comment by Telestosatt** [comment]
> Are you using installimage on a Hetzner Server or are you using this repository in your own infrastructure?

I am using `installimage` command

**Comment by asciiprod** [comment]
Then please open a support ticket with your config.

**Comment by Telestosatt** [comment]
> Then please open a support ticket with your config.

Added `CRYPTPASSWORD xxxxxxxx` in config (after partition portion) and It allowed me to proceed further 
(xxxxxxxx was a number)
Hope no issues will arise in future 😅

**Comment by mdengler** [comment]
> > I tried to install a new server, but I get this error after editing the config file. In the config file there is no comment for this setting. I tried `CRYPTPASSWORD 1234` but that didn't work either. Is there a possibility to install server without cryptpassword?
> > Thanks.
> 
> Facing same issue :(
> 
> > before I started `installimage` I had to set `CRYPT=0` I don't know if this behave as intended.
> 
> Tried this. But still facing same issue :(
> 
> Any idea how to fix it?

I had the same symptom, and the problem was a `PART` line that had an extra field, which the `functions.sh`/`installimage` script thinks[^1] is related to cryptsetup and then sets `CRYPT=1`:

WRONG/ERROR:
```
[...]
PART root / ext4 100G
[...]
```

...corrected:

```
[...]
PART / ext4 100G
[...]
```

This 

[^1]: The code is [functions.sh#772](https://github.com/hetzneronline/installimage/blob/master/functions.sh#L772): ```
[...]
  i=0
  while read -r PART_LINE ; do
    i=$((i+1))
    PART_MOUNT[$i]="$(echo "$PART_LINE" | awk '{print $2}')"
    PART_FS[$i]="$(echo "$PART_LINE" | awk '{print $3}')"
    PART_SIZE[$i]="$(translate_unit "$(echo "$PART_LINE" | awk '{ print $4 }')")"
    PART_CRYPT[$i]="$(echo "$PART_LINE" | awk '{print $5}')"
[...]
    if [ -n "${PART_CRYPT[$i]}" ]; then
      export CRYPT="1"
    fi
```

**Comment by Gogoro** [comment]
I had this same issue, and I thought I was going crazy. Finally found the issue, and I just wanted to share in case someone else find themselves in the same situation.

I had this configuration:

```
PART    /boot     ext3    2G # Should be enough
PART    lvm       vg0     all # Rest goes to LVM

LV    vg0     root    /           ext4    100G # filesystem should have 100G
LV    vg0     rook    /mnt/rook   xfs    all # The rest is going to be used by Rook
```

I should have understood it earlier, but as [this comment](https://github.com/hetzneronline/installimage/issues/34#issuecomment-1763267762) mentions. Having too many parameters will make the script think that it should use encryption.

I just removed my comments, and everything works as it should 🥳

**Comment by mdengler** [comment]
> I just removed my comments,

This indeed seems unexpected and fragile.  I edited my comment in case it helps others.  Once one knows, one'll never do it again, but maybe the maintainers will accept patches to make the behavior less surprising.

**Comment by kmille** [comment]
I had a similar issue. My solution:
```
CRYPT=0
CRYPTPASSWORD 1234
PART /     ext4 all
```
CRYPTPASSWORD is mandatory. I used `PART /     ext4 all crypt` from a previous installation...
