### ISSUE TITLE
Extended partitions

### ISSUE THREAD

**Issue by androidacy** [hetzneronline/installimage#35]
Most disk utilities, and both LVM2 and BTRFS, support including multiple disks in one partition.

The comments in the config file seem to indicate that extended partitions will be handled transparently. However, trying to set a size that will not fit on one disk fails, telling me that I don't have enough space. In addition,, the `all` seems to only fill up the rest of a single disk.

Is there a bug preventing the proper support of extended partitions, or is it possible to add it in the future?

**Comment by asciiprod** [comment]
Extended partitions are automatically created as needed. If you have a case where this does not work, please provide the corresponding config
