### ISSUE TITLE
Root on ZFS for supported distros

### ISSUE THREAD

**Issue by unixandria-xda** [hetzneronline/installimage#36]
Root on ZFS should work on Debian and Ubuntu; however it's not presented in `installimage` and the steps provided by OpenZFS for Ubuntu 20.04 do not result in a bootable system (instructions [here ](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html)for reference).

It seems, at a minimum, the live system would need to install zfsutils-linux from buster-backports, and the same would need installed in the new system (it's available from default repositories in ubuntu) as well as zfs-initramfs in the live system. There would also need to be handling of the creation of the suggested bpool and rpool (or user defined pools) and a standard BIOS Boot partition.

The config could look like follows:
```
PART zfs <pool name> <size> <---- defines that user wants to use zfs

zpool <pool name> <dataset> <mountpoint> <----- user defines datasets per pool
```
Where all `<dataset>` specified is relative to `<pool name>/`

For example, with a basic bpool and rpool, with no particular dataset besides / and /boot. /boot can be on ZFS, but that isn't as straightforward with swraid. Keep in mind, however, zfs has native RAID support at level 0 [just uses several disks] and then what you'd expect for level 1, 5, 6, and 10. Easiest solution would be to let ZFS handle the RAID if user selects it.
```
PART swap swap 32G
PART zfs bpool 2G
PART zfs rpool all

zpool bpool boot /boot
zpool rpool root /boot
```

Said config is not unlike what already exists for btrfs.

Would it be possible to add zfs support in the future? ZFS comes with many handy features, like recovering from silent corruption, compression, and built in RAID, amongst other things, and is suitable for most production environments,

**Comment by asciiprod** [comment]
Thank you for your suggestion. Due to the problematic licensing and possible GPL violation when doing so, we are not planning to add support for ZFS at any point.
