### ISSUE TITLE
Warning, GRUB_CMDLINE_LINUX_DEFAULT in /etc/default/grub is over written.

### ISSUE THREAD

**Issue by gnat** [hetzneronline/installimage#39]
Probably not actionable, but I wanted to note for users searching about this issue- your kernel options in `/etc/default/grub` for `GRUB_CMDLINE_LINUX_DEFAULT` are overwritten in `/etc/default/grub.d/hetzner.cfg`.

https://github.com/hetzneronline/installimage/blob/84883efa372b9c9ecef2bb7703d696221b4e1093/ubuntu.sh#L285

You may be better off setting your kernel options in `/etc/default/grub.d/hetzner.cfg` or removing it

Some example repercussions of this:
* Production Redis requires `transparent_hugepage=never`
* Rootless Docker requires `systemd.unified_cgroup_hierarchy=1` in current kernels to use cgroupsv2

Unsure if Hetzner can do anything about this, but just so people are aware when googling this issue.

Remember of course to `update-grub` when changing kernel options.

Thanks.

**Comment by fishnux** [comment]
Thank you!

Couldn't they add a comment to the grub file to indicate the file is overwritten?
