### ISSUE TITLE
Support for Fedora 35?

### ISSUE THREAD

**Issue by batistein** [hetzneronline/installimage#41]
I have seen that there is now also support for rocky linux, alma linux etc.
However, we use fedora in the cloud so far and would like to use this for our dedicated server as well. 
Is there a way to add this? @asciiprod I guess it's not that difficult since rocky, centos etc. are already very close to fedora? I would also be willing to make a PR, unfortunately I can not find documentation on how to include other operating systems, nor instructions on how to test installimage...

**Comment by asciiprod** [comment]
Please refer to: https://docs.hetzner.com/robot/dedicated-server/operating-systems/installing-custom-images
Fedora might be installable as CentOS without requiring changes to installimage. You need to create a tar achieve with the OS from a Fedora master image and then name it accordingly, like `CentOS-80-stream-amd64-fedora.tar.gz`.
If you like to extend installimage, there is unfortunately no guide how to do so.

**Comment by m3nu** [comment]
Also interested in adding a new image. CentOS 9 in that case. It's already available for Hetzner Cloud, but not metal servers.

Followed this [guide](https://community.hetzner.com/tutorials/create-and-install-custom-centos-8-image) minus the `systemd-networkd` stuff.

Installation is fine, but not booting for now. Maybe something minor. Waiting for my KVM now. 😄
