### ISSUE TITLE
[feature request] add support for Rancher Harvester HCI

### ISSUE THREAD

**Issue by christian-korneck** [hetzneronline/installimage#45]
it would be useful if it was possible to install Rancher Harvester HCI, an alternative to managed virtualization systems like Proxmox or VMWare Vsphere, via the Hetzner Rescue System / `installimage`. It [seems to be based](https://github.com/harvester/os2/blob/a021098eb114e6b1c78164bf6b6dbd5f28b70d13/Dockerfile#L3) on OpenSuSE Leap.

https://harvesterhci.io/
Image Downloads: https://github.com/harvester/harvester/releases

**Comment by asciiprod** [comment]
The OpenSuSE support in installimage is essentially unmaintained. As Hetzner no longer offers OpenSuSE preinstalled, it is likely to be dropped eventually

**Comment by christian-korneck** [comment]
I don’t think this is related to existing OpenSuSE images. It’s an appliance like image and doesn’t use the OpenSuSE installer, etc.

**Comment by asciiprod** [comment]
Installimage works by extracting and configuring pre-installed OS images. Hence it needs to support the distro it tries to configure.
