### ISSUE TITLE
RockyLinux 9 support

### ISSUE THREAD

**Issue by CDFN** [hetzneronline/installimage#53]
Hey, Rocky Linux 9 is already out. Is there any chance it gets added to installimage? :wink:

**Comment by asciiprod** [comment]
Support for Rocky 9 as well as Alma 9 will be added once testing has completed and the images are ready.

**Comment by CDFN** [comment]
Any updates on this? It's been a month, cloud has RL9 almost since it's release...

**Comment by pacofelc** [comment]
Any updates on this? It's been october yet...
