### ISSUE TITLE
Alma/Rocky Linux 9 support

### ISSUE THREAD

**Issue by pacofelc** [hetzneronline/installimage#57]
Hey, Rocky Linux 9 is already out. Is there any chance it gets added to installimage? 
Thank's in advance.

**Comment by asciiprod** [comment]
Yes, eventually support will be added.

**Comment by asciiprod** [comment]
installimage includes limited support for RHEL9-based images since 38226a51
However due to shim unconditionally modifying the boot order and being unremovable as an essential package, support for RHEL-based images will be limited.
https://github.com/rhboot/shim/issues/568

**Comment by leetsin** [comment]
Thanks a lot Hetzner People 👍😎

@asciiprod as you have custom motherboards, will a custom bios(uefi) solve the net boot problem ?

**Comment by kleisauke** [comment]
> and being unremovable as an essential package

shim is in fact removable, it's only marked as protected after commit https://src.fedoraproject.org/rpms/shim/c/f4bf84f7c52ca6b105e03ad22ef3f891d6b37364. 

One could remove shim by executing:
```console
$ dnf remove --setopt=protected_packages= "shim-*"
````

**Comment by asciiprod** [comment]
While that may allow removing shim, grub has been modified in these distributions and can no longer create an EFI binary. 
https://bugzilla.redhat.com/show_bug.cgi?id=1917213

**Comment by kleisauke** [comment]
... it looks like https://bugzilla.redhat.com/show_bug.cgi?id=1917213 is now resolved via commit https://src.fedoraproject.org/rpms/grub2/c/8a9297c4314b61eac1f47ab6444615eb9f13874d. You'll have to use the `--force` option to create the EFI boot entry.

**Comment by leonardehrenfried** [comment]
What about the suggestion to use efibootmgr instead of grub-install?

Wouldn't that be the better solution?

**Comment by kleisauke** [comment]
I just requested a backport for that commit to RHEL 9 in PR https://github.com/rhboot/grub2/pull/135.

**Comment by kleisauke** [comment]
... that commit has just been backported to RHEL 9, see:
https://gitlab.com/redhat/centos-stream/rpms/grub2/-/commit/6c0546793ae19d7a217cd7add5b7a493bfad41a6

It should be available in the upcoming RHEL 9.4.0. :tada:

**Comment by leonardehrenfried** [comment]
Sorry for the nag but is it going to be possible to use CentOS 9 now that the above fix has been added?

**Comment by kleisauke** [comment]
It looks like Hetzner now offers support for AlmaLinux 9, CentOS Stream 9 and Rocky Linux 9 on the [AX41-NVMe](https://www.hetzner.com/dedicated-rootserver/ax41-nvme/) servers:
https://www.hetzner.com/dedicated-rootserver/matrix-ax#software-2286

**Comment by kleisauke** [comment]
> It should become available in the upcoming RHEL 9.4.0 release.

Unfortunately, this change was not shipped in RHEL 9.4.

**Comment by kleisauke** [comment]
This fix has just been shipped in `grub2-2.06-80.el9_4`, so ignore my previous comment. See for reference:
https://github.com/openela-main/grub2/commit/98b580a7c4a34170534dcae70a54199f60b7150e
https://git.rockylinux.org/staging/rpms/grub2/-/commit/b524202569789ead872d1d71d35257f1e9d8a601
https://git.almalinux.org/rpms/grub2/commit/373fa37ba6d6083bb1a96c90494d0ca2309bb4a4

**Comment by pat-s** [comment]
I was able to install a fresh Alma9 on an AX42 [-> instructions](https://forums.almalinux.org/t/upgrade-8-8-to-9-2-using-leapp-does-not-boot-into-elevate-upgrade-initramfs/2566/5?u=pat-s).
