### ISSUE TITLE
Ubuntu22.04 not using the rescue system credentials

### ISSUE THREAD

**Issue by deemonrider** [hetzneronline/installimage#59]
Hey!

So I use ssh credentials to connect to the rescue system, installed ubuntu 22.04 with the basic config, rebooted the server and then I got asked for a username and password - the ssh key didn't work. (I only set a ssh key when ordering the server)
I tried multiple times installing this even with params  like -t or -G to take over the SSH keys but that also didn't work.

Now after 5 reinstallations I went to ubuntu 20.04 and there it worked fine and I could connect with my SSH-Key right after the installation.

**Comment by mafalb** [comment]
Reading your description it is not clear to me: Is the ssh key deployed but not working afterwards (which I believe could be the case if it's an older type of ssh key (dsa)) or  is it not deployed at all?

**Comment by fsrv-xyz** [comment]
Since Ubuntu 22.04, the most RSA keys (with SHA-1 hash algorithm) are not working any more. See https://askubuntu.com/a/1409528 for more information.
