### ISSUE TITLE
default installimage.conf places swap as first partition

### ISSUE THREAD

**Issue by stapelberg** [hetzneronline/installimage#6]
…this makes removing the swap partition very inconvenient after installation. It would be easier if the swap partition was placed last in the partition table.

This was observed on an ex61 server.

**Comment by asciiprod** [comment]
As always there are pros and cons for this default. And for exactly this reason a custom partition scheme can be passed.

**Comment by stapelberg** [comment]
What’s the pro of this default?

**Comment by stapelberg** [comment]
Thanks for the detailed explanation!
