### ISSUE TITLE
Follow up on  RockyLinux 9 support

### ISSUE THREAD

**Issue by gsnick** [hetzneronline/installimage#68]
Hello,
The issue #53 was closed. 
Could you please update on it? 

Thank you.

**Comment by leetsin** [comment]
https://www.redhat.com/en/blog/rhel-9-networking-say-goodbye-ifcfg-files-and-hello-keyfiles
The above is one of the things the engineers must change from EL-7/8.
There may be many such system changes that need to be rewritten. It is not easy for the engineers. We will have to wait.

**Comment by gsnick** [comment]
Hello,
But it is available for hetznercloud since a long time already...
Could you please why it is so?
Thank you.

**Comment by asciiprod** [comment]
Hetzner Cloud instances uses a fixed disk image. Each instance is essentially the same and customization is done via cloud-init.
Installimage needs to support RAID, LVM, multiple filesytems and has to generate and change the corresponding configs. While many parts can be reused, there have been a lot of changes in RHEL9. 
As mentioned in #53 we will release the image as well as the patches for installimage when they are ready. Currently there is no planned date for this.

**Comment by leetsin** [comment]
You could ask Rocky forums for help, as this is open source.

**Comment by albertoridolfi** [comment]
Bump. Any updates on this? Is this planned at all? I have some customers on Hetzner dedicated servers who are considering moving off to other providers because of this. RHEL9 and its family (CentOS Stream 9, Rocky and Alma) have been out for almost a year now. It's too important of a platform to be a second-class citizen.

**Comment by paviln** [comment]
Is there a ETD?

**Comment by BlackTiger63** [comment]
Nope nothing yet.
Asked last week, today I got this answer from Hetzner:

"at the moment we only offer Alma Linux 8.7 if you require another version it´s possible to install it by yourself manually."

**Comment by albertoridolfi** [comment]
CentOS Stream 9, Alma Linux 9 and Rocky Linux 9 are already showing up on Hetzner installimage

**Comment by BlackTiger63** [comment]
Any idea since when? Because I know it's available already for cloudvps systems.
So you mean it's not yet on the systems in the Robot, but if you start installimage from safe mode it's there, on dedi's?

**Comment by albertoridolfi** [comment]
When I go to Robot and start the rescue system on a dedicated server, and then run "installimage", they are there.
