### ISSUE TITLE
Wrong image reference

### ISSUE THREAD

**Issue by GarrySinitsin** [hetzneronline/installimage#69]
When I choose image Ubuntu 20.04 focal minimal hwe - I obtained Debian 11 (tried twice). 
![1](https://user-images.githubusercontent.com/8254391/221570780-dc33702d-9eda-4046-8809-dfca19e201eb.jpg)
![2](https://user-images.githubusercontent.com/8254391/221570786-c079f1bb-751d-40f3-8438-afbc55ceec5c.jpg)
![3](https://user-images.githubusercontent.com/8254391/221570788-cd33ff54-9aba-4bce-a712-5d129ffd9384.jpg)

**Comment by fsrv-xyz** [comment]
Hi, 
I tried to reproduce the described behavior.
Did you run the `lsb_release -a` command inside the rescue environment after the installimage command?
This would explain the deviation.


Executed in the installed image, the command brought the expected output.

![image](https://user-images.githubusercontent.com/35347506/221780177-2f543d50-a49e-453e-926d-64cf4edf7ca4.png)

Could you please provide the contents of the `/etc/hetzner-build` file?
