### ISSUE TITLE
support for ClearLinux

### ISSUE THREAD

**Issue by TermeHansen** [hetzneronline/installimage#71]
I would like to test out the "cloudfirst" OS, ClearLinux. It does not support grub, and for this reason I'm waiting for my KVM, as I see that as the only way.

I guess their OpenStack image (Cloud Guest" is not far from being possible to use?
https://clearlinux.org/downloads

I would love to see this OS as one of the support ones...

**Comment by asciiprod** [comment]
Sorry, it's unlikely to be ever implemented
