### ISSUE TITLE
Support for Fedora CoreOS

### ISSUE THREAD

**Issue by silenium-dev** [hetzneronline/installimage#72]
I'd like to use Fedora CoreOS (https://docs.fedoraproject.org/en-US/fedora-coreos/) with the Cluster API Provider Hetzner (https://github.com/syself/cluster-api-provider-hetzner), but it requires any setup of bare metal machines to be made with `installimage`, which currently doesn't support it, because it has a different filesystem structure than common Linux distributions. It uses an ostree based root filesystem for A/B-deployments and rollbacks. This requires btrfs with snapshots and a different `/boot` layout.

**Comment by silenium-dev** [comment]
How do I test my changes? Is there any test environment (VM image, packer config) or do I have to use a dedicated server with its rescue system? And on the rescue system, how do I replace the already present `installimage` with my own, because I have only read permissions on the NFS mount, but the `installimage` script requires being in a specific directory.

**Comment by yaroze** [comment]
> I will give it a try, am I allowed to use the coreos-installer (requires rustup and cargo install on the rescue system) or should I write the config manually.
> To configure CoreOS, should I assemble the ignition config from the given options (DRIVE1, DRIVE2, SWRAID etc.) or add a CoreOS specific option to pass an url where the installer can download the config? Using an url to download the ignition config would allow much more customization.

Hi!
I've been developing a Dockerfile that creates an image you can use to generate and inject an ignition file on Fedora CoreOS. 

You can then test it on qemu or another hypervisor that supports qcow2. If it works, you might be able to deploy it on Hetzner servers through the rescue system, but I give no guarantees, as I'm not (yet) a Hetzner customer.

You can find it on my GH repo [@](https://github.com/yaroze/oci-fcos).

**Comment by silenium-dev** [comment]
> Hi!
> I've been developing a Dockerfile that creates an image you can use to generate and inject an ignition file on Fedora CoreOS. 
> 
> You can then test it on qemu or another hypervisor that supports qcow2. If it works, you might be able to deploy it on Hetzner servers through the rescue system, but I give no guarantees, as I'm not (yet) a Hetzner customer.
> 
> You can find it on my GH repo [@yaroze/oci-fcos](https://github.com/yaroze/oci-fcos).

This doesn't help me, because I have to use the `installimage` method as described in the issue. For installing coreos with an ignition file, there is already the official coreos-installer which does exactly that: write coreos and the ignition file onto a disk. It's available as a container image, too.

**Comment by yaroze** [comment]
>
the official coreos-installer which does exactly that: write coreos and the ignition file onto a disk. It's available as a container image, too.
>
Not quite... it's a bit different from coreos-installer.
Coreos-installer takes an ISO and deploys FCOS on the same machine it is running.

My dockerfile takes a vanilla FCOS qcow2 image and embeds the ignition file into it, which can then be used on a VM running on qemu. That was my purpose, as I want to run FCOS on Oracle Cloud, which doesn't also support ignition files. However, they support qcow2 images, hence my specific use case.

If that feature was available in coreos-installer, I wouldn't take the effort of developing something that has already been developed 😅

In your case, you could convert the resulting qcow2 image to raw and use dd to dump it to your server.

I don't know about Hetzner's rescue system, but you can do the dd over ssh if, for some reason, you can't upload the raw image to the filesystem of the rescue system.

**Comment by yaroze** [comment]
>the official coreos-installer which does exactly that: write coreos and the ignition file onto a disk. It's available as a container image, too.


Not quite... it's a bit different from coreos-installer.
Coreos-installer takes an ISO and deploys FCOS on the same machine it is running.

My dockerfile takes a vanilla FCOS qcow2 image and embeds the ignition file into it, which can then be used on a VM running on qemu. That was my purpose, as I want to run FCOS on Oracle Cloud, which doesn't also support ignition files. However, they support qcow2 images, hence my specific use case.

If that feature was available in coreos-installer, I wouldn't take the effort of developing something that has already been developed 😅

In your case, you could convert the resulting qcow2 image to raw and use dd to dump it to your server.

I don't know about Hetzner's rescue system, but you can do the dd over ssh if, for some reason, you can't upload the raw image to the filesystem of the rescue system.

**Comment by silenium-dev** [comment]
> I don't know about Hetzner's rescue system, but you can do the dd over ssh if, for some reason, you can't upload the raw image to the filesystem of the rescue system.

`installimage` runs on the rescue system which is booted via PXE. It doesn't run from disk so you can write directly to it. So I don't need to write from somewhere else or somehow else. I just need to integrate the correos-installer with `installimage`.

**Comment by asciiprod** [comment]
Closing as unlikely to happen due to FCOS completely different approach
