### ISSUE TITLE
Set vm.swappiness = 10 for bare metal servers and for virtual machine servers

### ISSUE THREAD

**Issue by makhomed** [hetzneronline/installimage#75]
Current installimage settings:
``` bash
  # only swap to avoid a OOM condition on vps
  if is_virtual_machine; then
   echo "vm.swappiness=0" >>$sysctl_conf
  fi
```
It means what for virtual machine servers ```vm.swappiness``` will be ```0``` and for bare metal servers ```vm.swappiness``` will be ```60```.

May be for servers setting ```vm.swappiness = 10``` will be better? for bare metal servers and for virtual machine servers.

Low values of ```vm.swappiness``` useful not only for virtual machines, but also for hardware virtualization supervisors like QEMU.

Fragment of [Red Hat Enterprise Linux 9 documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/monitoring_and_managing_system_status_and_performance/index#virtual-memory-parameters_configuring-an-operating-system-to-optimize-memory-access):

> vm.swappiness
> 
> The swappiness value, ranging from 0 to 200, controls the degree to which the system favors reclaiming memory from the anonymous memory pool, or the page cache memory pool.
> 
> Setting the swappiness parameter’s value:
> 
> Higher values favor file-mapped driven workloads while swapping out the less actively accessed processes’ anonymous mapped memory of RAM. This is useful for file-servers or streaming applications that depend on data, from files in the storage, to reside on memory to reduce I/O latency for the service requests.
> 
> Low values favor anonymous-mapped driven workloads while reclaiming the page cache (file mapped memory). This setting is useful for applications that do not depend heavily on the file system information, and heavily utilize dynamically allocated and private memory, such as mathematical and number crunching applications, and few hardware virtualization supervisors like QEMU.
> 
> The default value of the vm.swappiness parameter is 60.
> 
> Warning
> 
> Setting the vm.swappiness to 0 aggressively avoids swapping anonymous memory out to a disk, this increases the risk of processes being killed by the oom_killer function when under memory or I/O intensive workloads.
> 
>

**Comment by asciiprod** [comment]
While this may benefit certain workloads, we don't change the default unless needed.

**Comment by makhomed** [comment]
> While this may benefit certain workloads, we don't change the default unless needed.

The default value of the vm.swappiness parameter is 60.

You already change default in the installimage code, you set ``vm.swappiness=0``

But your change is dangerous, and can lead to Out-Of-Memory errors:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/patch/?id=fe35004fbf9eaf67482b074a2e032abb9c89b1dd

> This patch changes the behavior with swappiness==0.  If we set swappiness==0, the kernel does not swap out completely (for global reclaim until the amount of free pages and filebacked pages in a zone has been reduced to something very very small (nr_free + nr_filebacked < high watermark)).

https://chrisdown.name/2018/01/02/in-defence-of-swap.html

> When talking about vm.swappiness, an extremely important change to consider from recent(ish) times is [this change to vmscan by Satoru Moriya in 2012](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/patch/?id=fe35004fbf9eaf67482b074a2e032abb9c89b1dd), which changes the way that vm.swappiness = 0 is handled quite significantly.

> Essentially, the patch makes it so that we are extremely biased against scanning (and thus reclaiming) any anonymous pages at all with vm.swappiness = 0, unless we are already encountering severe memory contention. As mentioned previously in this post, that's generally not what you want, since this prevents equality of reclamation prior to extreme memory pressure occurring, which may actually lead to this extreme memory pressure in the first place. vm.swappiness = 1 is the lowest you can go without invoking the special casing for anonymous page scanning implemented in that patch.

https://www.percona.com/blog/oom-relation-vm-swappiness0-new-kernel/

> This obviously changed the way we think about “vm.swappiness=0”. Previously, setting this to 0 was thought to reduce the tendency to swap userland processes but not disable that completely. As such it was expected to see little swapping instead of OOM.

===========================================

```vm.swappiness=0``` means: swap is disabled completely, this can lead to OOM errors
```vm.swappiness=1``` means: minimum amount of swapping without disabling it entirely
```vm.swappiness=10``` recommended value to improve performance when sufficient memory exists in a system
```vm.swappiness=10``` is the best performance value for all bare metal servers and virtual machine servers

I understand your motivation to set ```vm.swappiness=0``` on each server - to minimize SSD wearing and save money. This is good motivation.  But setting ```vm.swappiness=0``` is dangerous, because it can lead to unexpected OOM errors and ```vm.swappiness=0``` reduce overall performance of virtual and bare metal servers in most cases.

**Comment by asciiprod** [comment]
as noted in the code comment: this is done to avoid a OOM condition on vps which have no swap by default.
If you have a different opinion for your use case, you are free to change this settings either via post-install or any other means.
