### ISSUE TITLE
update-initramfs not working in post-install scripts

### ISSUE THREAD

**Issue by uplight-dev** [hetzneronline/installimage#78]
It looks like update-initramfs is not working if added to post-install scripts.

`update-initramfs -c -k $(uname -r)`

It fails with error:

```
W: missing /lib/modules/6.3.1
W: Ensure all necessary drivers are built into the linux image!
depmod: ERROR: could not open directory /lib/modules/6.3.1: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
cat: /var/tmp/mkinitramfs_8VyE8z/lib/modules/6.3.1/modules.builtin: No such file or directory
find: '/var/tmp/mkinitramfs_8VyE8z/lib/modules/6.3.1/kernel': No such file or directory
W: Can't find modules.builtin.modinfo (for locating built-in drivers' firmware, supported in Linux >=5.2)
depmod: WARNING: could not open modules.order at /var/tmp/mkinitramfs_8VyE8z/lib/modules/6.3.1: No such file or directory
depmod: WARNING: could not open modules.builtin at /var/tmp/mkinitramfs_8VyE8z/lib/modules/6.3.1: No such file or directory

```

**Comment by uplight-dev** [comment]
Any idea if it's possible to use update-initramfs inside the post-install script?

**Comment by asciiprod** [comment]
Yes, it is possible, but you cannot reference the kernel of the to be installed system using `uname` as this points to the kernel of the rescue system.
In general, this is not an official support channel. Please open a ticket in your customer account if you have questions about Hetzner products and tools.

**Comment by uplight-dev** [comment]
ok but then what is the correct command to use to update-initramfs?
how do I find which kernel to update from inside the chrooted env?

I've also tried:
`update-initramfs -c -k all`
but I still get errors.
