### ISSUE TITLE
Add support for either Alma Linux 9 or Rocky Linux 9

### ISSUE THREAD

**Issue by mbabuskov** [hetzneronline/installimage#79]
I have a bunch of dedicated servers with you that currently run CentOS 7 which will EOL on June 2024. I plan to move all of these to either Rocky 9 or Alma 9. Without installimage support it will be cumbersome because I want to setup full disk encryption on all new systems and it would mean having to schedule KVM for each machine.

I am certain that many other sysadmins have the same problem because Rocky/Alma are currently the most popular systems that offer long term (7+ years) support.

Can you please let us know whether Rocky 9 or Alma 9 support is planned and when can we expect it approximately?

Thanks.

**Comment by asciiprod** [comment]
See #57
