### ISSUE TITLE
Rocky Linux 9, AlmaLinux 9, and CentOS Stream 9 UEFI Support

### ISSUE THREAD

**Issue by CtrlAltF7** [hetzneronline/installimage#86]
Since RHEL 9 and its derivatives were released in May 2022, could the following check be removed? It prevents the usage of all recent RHEL distros in UEFI systems.

https://github.com/hetzneronline/installimage/blob/85e93b43a30955dca5558b44ae844628cd8f0433/functions.sh#L1009-L1012

**Comment by asciiprod** [comment]
Please see 
https://github.com/hetzneronline/installimage/issues/57#issuecomment-1569642504
