### ISSUE TITLE
netplan error: gateway6 has been deprecated with latest ubuntu 20.04 image

### ISSUE THREAD

**Issue by landorg** [hetzneronline/installimage#87]
Hi.
I'm ending up [here](https://github.com/hetzneronline/installimage/blob/85e93b43a30955dca5558b44ae844628cd8f0433/network_config.functions.sh#L806) with:

```
[18:10:19] fatal: netplan generate stderr not empty:
[18:10:19] :
[18:10:19] :   ** (generate:3): WARNING **: 18:10:19.467: `gateway6` has been deprecated, use default routes instead.
[18:10:19] :   See the 'Default routes' section of the documentation for more details.
[18:10:19] => FAILED
```
using the most recent 20.04 ubuntu image.

Maybe [this](https://github.com/hetzneronline/installimage/blob/85e93b43a30955dca5558b44ae844628cd8f0433/network_config.functions.sh#L658) needs to be updated to:
```bash
    [[ "$IAM" == ubuntu ]] && ((IMG_VERSION < 2004)) && force_pre_103_style=1
```
Using this image: https://releases.ubuntu.com/jammy/ubuntu-22.04.3-live-server-amd64.iso

Any idea how to work around this?
Thanks

**Comment by asciiprod** [comment]
Installimage works with tar archives. It does not support ISO images.
For custom images you can find the requirements here:
https://docs.hetzner.com/robot/dedicated-server/operating-systems/installing-custom-images/#install-older-linux-images-using-the-installimage-script
