### ISSUE TITLE
Setup guide for installimage

### ISSUE THREAD

**Issue by AlexisDucastel** [hetzneronline/installimage#88]
Hi everyone ! 

The hetzner installimage tool is just amazing by its simplicity of use, automation, configuration and speed of install.

I would like to use it to fasten my lab servers installation at home (I install/reinstall them very often for education purpose), but I struggle getting it fully functionnal (All I did is try-and-die with walking errors after erros until no error, but the installation did not worked after reboot).

Is there any documentation on how to setup installimage ?

Thanks a lot for your help !

**Comment by AlexisDucastel** [comment]
I precise that I do not expect a complete documentation about how to setup it in every situation, but just some "hints" to help people.

For example, I found that installimage must be setup in /root folder, images must be cloudinit images and must be present inf a specific folder, the scripts require "theses" packets.

Right now here is my "init script", which does not work fully but may be a starting point. 
```
apt update && apt install -y \
	git \
	bc \
	dialog \
	mcedit \
	dmraid \
	systemd-container

cd /root
git clone https://github.com/hetzneronline/installimage.git
alias installimage='/root/installimage/installimage'
```

I would really appreciate a bit of help on this :) Thanks.

**Comment by asciiprod** [comment]
Unfortunately there is no detailed guide to do this. But you need to have a working live linux environment which contains the necessary tools (mdadm, parted, sgdisk, sfdisk, etc.).
Then you should be able to simply create an alias to where installimage is stored (it does not have to be in the root directory). You will also have to adjust URLs and paths in config.sh.

**Comment by AlexisDucastel** [comment]
Okay. Is it wanted to not have a documentation about that because it is an open-source-proprietary solution that you don't want to see used by other providers ? Or can someone help providing this ?

**Comment by asciiprod** [comment]
We provide the source code it as-is. Mainly so our customers can have a look at the code. If you find it useful and like to use it, you are free to do so, but we don't provide any help or support in getting it to work.
There is a fork which uses installimage with a Archlinux based rescue image. It has a bit more documentation which may help you:
* https://github.com/virtapi/installimage
* https://github.com/virtapi/LARS

**Comment by AlexisDucastel** [comment]
Okay no problem :) 

Thanks a lot for your help @asciiprod  :)

**Comment by AlexisDucastel** [comment]
I'm closing this request as it it out-of-scope.
