### ISSUE TITLE
installimage version on Server (via NFS) is different

### ISSUE THREAD

**Issue by guettli** [hetzneronline/installimage#89]
Today we see that installimage behaves differently.

We guess that the script `installimage` has changed.

I attached the diff between the current master on Github and the code which is on the server (mounted on `/root/.oldroot/nfs/install/`):

[installimage-diff.txt](https://github.com/hetzneronline/installimage/files/13054441/installimage-diff.txt)

It would be great, if we could see the latest version here on github, so that we can more easily see what has changed.

Please update the code here at Github.

**Comment by guettli** [comment]
Our image-name did no match, so it failed on these lines (which are not published here yet)

```
  if [[ "$IMG_ARCH" == 'unknown' ]]; then
    graph_error "ERROR: can not determine image arch from filename"
    return 1
  fi
```

**Comment by asciiprod** [comment]
We have added additional validation to prevent accidental installing arm64 images on x86 rescue systems:
https://github.com/hetzneronline/installimage/blob/master/functions.sh#L966

**Comment by guettli** [comment]
thank you.
