### ISSUE TITLE
UEFI installation doesn't create RAID1 for ESP partition

### ISSUE THREAD

**Issue by nazar-pc** [hetzneronline/installimage#91]
I just did fresh UEFI installation and found that ESP partition was created with the same UUID twice, once on each device, instead of creating RAID1 like https://docs.hetzner.com/robot/dedicated-server/operating-systems/efi-system-partition/ recommends.

This is fixable manually, but would be great to have installimage do it automatically.

**Comment by asciiprod** [comment]
Using RAID1 as outlined in the article is a bit of a hack. It works, but the right way is to actually have separate ESPs on every device. Ubuntu, which you have probably selected, supports this and installimage will install it this way.

**Comment by nazar-pc** [comment]
Both will need to be updated if GRUB is updated, does it also install some hook that copies files properly from one ESP partition to another? Not sure how that would be done if UUID of both partitions was the same and `/etc/fstab` was mounting partition by UUID. The hack in the article ensures both have up to date config and it was quite an effort to adjust partition table and OS accordingly before the first boot.

**Comment by asciiprod** [comment]
No, there is no hack that needs to be installed. As mentioned Ubuntu supports multiple ESPs natively. This means when grub is updated it gets installed on all configured ESPs. They get the same id so that at least one of them is always mounted.

**Comment by nazar-pc** [comment]
Wow, that is a bit surprising and confusing at the same time, I didn't know about it. Thanks for explaining!

**Comment by nazar-pc** [comment]
But why does the article recommends RAID1 anyway then?

**Comment by asciiprod** [comment]
It's still a working solution and for everything but Ubuntu there are no other (easy) options for redundancy available.

**Comment by tsipizic** [comment]
Thank you for the clarification on all these issues. In that case what is the recommended action when replacing broken hard drives? Is the command below sufficient, after preparing the new drive with the same partition table?
```
mkfs.fat -F16 -i $(blkid -o value -s UUID /dev/nvme0n1p1| sed 's/-//g') /dev/nvme1n1p1
dpkg-reconfigure grub-efi-amd64 (selecting both ESP)
```
Maybe the [Exchanging hard disks in a Software-RAID](https://docs.hetzner.com/robot/dedicated-server/raid/exchanging-hard-disks-in-a-software-raid/) article should be updated for UEFI systems.
