### ISSUE TITLE
ERROR: can not determine image arch from filename

### ISSUE THREAD

**Issue by flg77** [hetzneronline/installimage#93]
Hi, 

I am receiving the *arch* error again. 
-file name includes arch type as requested. 
[debug.txt](https://github.com/hetzneronline/installimage/files/13364689/debug.txt)

``` 
DISTRIB ID:               centos
[12:43:46] :   DISTRIB RELEASE/CODENAME: 92
[12:43:46] :   ERROR: can not determine image arch from filename
[12:43:46] cleaning up
```

**Comment by fsrv-xyz** [comment]
Hello @flg77,
I have tried to reproduce the behavior you described. As far as I can see, there is no problem with the regular installation process of CentOS Stream 9.
Could you please attach your `config.txt` as well as your installation parameters?

**Comment by flg77** [comment]
I think I've found the issue.  The install completed now. It was a customized image.

**Comment by fsrv-xyz** [comment]
Thank you for the note. @flg77
What did cause the problem in your custom image?
