### ISSUE TITLE
almalinux 92 on EFI systems

### ISSUE THREAD

**Issue by Jiroun** [hetzneronline/installimage#99]
when try to install almalinux 9 using installimage

I got this error 

ERROR: we do not yet support almalinux 92 on EFI systems

is this possible to be fixed soon ?

or is there anyway I can install it myself ?

Thanks

**Comment by kleisauke** [comment]
I think AlmaLinux 9 (and other RHEL 9 derivatives) isn't officially supported yet, see: #57.

That said, it seems that the installimage version via NFS is different from what is here on GitHub (similar to issue #89), at least on the [AX41-NVMe](https://www.hetzner.com/dedicated-rootserver/ax41-nvme/) server. For example, it has this change:
```diff
--- a/functions.sh
+++ b/functions.sh
@@ -1024,7 +1024,7 @@ validate_vars() {
     graph_error "ERROR: CentOS 6 is EOL since Nov 2020 and installimage does not support CentOS 6 anymore"
     return 1
   fi
-  if (( UEFI == 1 )) && rhel_9_based_image; then
+  if (( UEFI == 1 )) && rhel_9_based_image && test -z "$RHEL9_UEFI_OVERRIDE" ; then
     graph_error "ERROR: we do not yet support $IAM $IMG_VERSION on EFI systems"
     return 1
   fi
```

which means that this check is disabled whenever the `RHEL9_UEFI_OVERRIDE` variable is not set. However, I suspect that only the [AX41-NVMe](https://www.hetzner.com/dedicated-rootserver/ax41-nvme/) servers have this change.

**Comment by uzairjhandir** [comment]
i have hetzer dedicated server i dont want to install almalinux 8
 
when try to install almalinux 9 using installimage

I got this error

ERROR: we do not yet support almalinux 92 on EFI systems

is this possible to be fixed soon ?

or is there anyway I can install it myself ?

Thanks

**Comment by duderuud** [comment]
@uzairjhandir Yes you can:
https://www.endpointdev.com/blog/2023/07/rocky-linux-9-at-hetzner-robot-made-quick-and-easy/

But look at the comments, it's a workaround. Just make sure you exclude grub2 from updating:
edit /etc/yum.conf and add line
exclude=grub2-*

Again, this is a workaround and not a long term solution.

**Comment by rafelamer** [comment]
Hi,
I have the same problem with a AX102 server and I need to install Rocky Linux.
what can I do?
Best regards,
Rafel Amer

**Comment by duderuud** [comment]
Install Alma9 and change
/boot/efi/EFI/almalinux/grub.cfg:
search --no-floppy --root-dev-only --fs-uuid --set=dev <uuid>
to
search --no-floppy --fs-uuid --set=dev <uuid>

So remove  "--root-dev-only"

No guarantees it will survive an update so test it before using it in a prod environment

**Comment by rafelamer** [comment]
Hi,
but how can I install Rocky Linux 9.2?  I'm not able to install it.

When I run installimage, I get the error
ERROR: we do not yet support rockylinux 92 on EFI systems

Best regards,
Rafel Amer

**Comment by duderuud** [comment]
Start rescue mode and run:
_cp /root/images/Alma-92-amd64-base.tar.gz /root/Alma-87-amd64-base.tar.gz_
installimage -> custom image
edit "hostname" and "image": _IMAGE /root/Alma-87-amd64-base.tar.gz_
Press F10 and save

**Comment by SeanBremner** [comment]
Hi there duderuud! :)

Thank you so much for always coming back to this topic & offering these tips - they've really helped me successfully install Almalinux 9 on a new AX42 server from Hetzner.

I managed to have mine working fine for more than a day, and a series of reboots were done without any issue between installs of other software like Plesk, Litespeed & Redis - however it has now just failed again, despite the exclusion of grub2 from yum's update.

Is there any way to recover it in the current state, or will I need to wipe it clean & reinstall Almalinux 9 from scratch again? Also, do you have any further ideas of what could've possibly caused it to fail like this?

I'm in the middle of migrating from a server running CentOS 7 to a new one, which I was hoping could've run Alma 9, and have various trial periods which will only last 14 days - so I'm working against the clock here haha!

**Comment by duderuud** [comment]
No problem, happy to help.

It isn't possible to restore a snapshot so you have to reinstall using the rescue mode described above.

Without knowing any details it's impossible to tell what went wrong.

Not a 100% sure if the latest Grub patches are applied in Alma 9 already but just to be certain:
- Install Alma9 as I described above
- Run a "dnf update"
- "vi /boot/efi/EFI/almalinux/grub.cfg" -> remove “--root-dev-only”
- "grub2-mkconfig -o /boot/efi/EFI/almalinux/grub.cfg"
- Reboot

That should fix the Grub issues.

And if you are up for some broadening of your horizon, check out [Centminmod](https://centminmod.com)
Fantastic software stack which is reliable, easy to understand once you read into it and above all FAST!

I use it on all my servers, it's really great.
